"""Helpers that write machine-readable results, LaTeX tables and LaTeX value macros.

Every number quoted in the manuscript is produced by a notebook and written
either to ``results/data/*.json`` / ``results/tables/*.csv`` or to the macro
file ``manuscript/generated/results_macros.tex``; nothing is typed by hand.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

from .paths import DATA, GENERATED_TEX, RESULTS, TABLES

__all__ = ["to_builtin", "save_json", "load_json", "fmt_sig", "fmt_sci", "latex_table", "write_macros"]


def to_builtin(obj):
    """Recursively convert NumPy scalars/arrays to JSON-serialisable built-ins."""
    if isinstance(obj, dict):
        return {str(k): to_builtin(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_builtin(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return to_builtin(obj.tolist())
    if isinstance(obj, (np.floating,)):
        return to_builtin(float(obj))
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None  # JSON has no NaN/inf; null is read back as NaN by pandas
    return obj


def save_json(data: dict, name: str, directory: Path = DATA) -> Path:
    """Write ``data`` to ``directory/name`` (pretty-printed, sorted keys)."""
    path = Path(directory) / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(to_builtin(data), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def load_json(name: str, directory: Path = DATA) -> dict:
    return json.loads((Path(directory) / name).read_text(encoding="utf-8"))


def fmt_sig(x: float, sig: int = 3) -> str:
    """Format with ``sig`` significant figures in plain notation (no trailing exponent)."""
    if x == 0 or not np.isfinite(x):
        return str(x)
    digits = sig - int(math.floor(math.log10(abs(x)))) - 1
    digits = max(digits, 0)
    return f"{round(x, digits):.{digits}f}"


def fmt_sci(x: float, sig: int = 2, math_mode: bool = True) -> str:
    """Format as a LaTeX scientific number, e.g. 1.2\\times10^{-5}."""
    if x == 0:
        return "0"
    if not np.isfinite(x):
        return str(x)
    exp = int(math.floor(math.log10(abs(x))))
    mant = x / 10**exp
    if round(abs(mant), sig - 1) >= 10:
        mant /= 10
        exp += 1
    s = f"{mant:.{sig - 1}f}\\times10^{{{exp}}}"
    return f"${s}$" if math_mode else s


def latex_table(rows, columns, path: Path, column_format: str | None = None) -> Path:
    """Write a booktabs tabular (body only, no float environment) for \\input in the manuscript.

    ``rows`` is a list of lists of already-formatted strings; ``columns`` the
    header strings.
    """
    column_format = column_format or ("l" + "c" * (len(columns) - 1))
    lines = [f"\\begin{{tabular}}{{{column_format}}}", "\\toprule", " & ".join(columns) + " \\\\", "\\midrule"]
    for r in rows:
        if r == "midrule":
            lines.append("\\midrule")
        else:
            lines.append(" & ".join(r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("% Generated by notebooks/04_publication_figures.ipynb -- do not edit by hand.\n"
                    + "\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_macros(macros: dict, path: Path = GENERATED_TEX / "results_macros.tex") -> Path:
    """Write \\newcommand definitions; macro names must be alphabetic."""
    lines = ["% Generated by notebooks/04_publication_figures.ipynb -- do not edit by hand."]
    for name, value in sorted(macros.items()):
        if not name.isalpha():
            raise ValueError(f"Macro name {name!r} must contain letters only.")
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


FINAL_RESULTS = RESULTS / "final_results.json"
