"""Post-process the latexdiff output so that the marked manuscript compiles cleanly.

latexdiff is applied to a near-complete rewrite (original/main.tex ->
manuscript/main_revised_clean.tex).  Three constructs of the deleted original
text break LaTeX after word-level diffing; this script repairs them without
changing any added (new) text:

1. labels inside deleted display math (``align*``) are removed, because the
   deleted equations are unnumbered and would otherwise raise amsmath errors;
2. blank lines (paragraph breaks) that latexdiff carries into ``\\caption{...}``
   arguments from deleted paragraphs are removed;
3. the deleted hand-written ``thebibliography`` of the original is replaced by a
   comment (the new bibliography is unchanged).

Usage:  python tools/fix_latexdiff.py manuscript/main_revised_marked.tex
"""
import re
import sys
from pathlib import Path


def strip_labels_in_deleted_math(text: str) -> str:
    def repl(m):
        block = m.group(0)
        return re.sub(r"\\label\{[^}]*\}", "", block)
    return re.sub(r"\\begin\{align\*\}.*?\\end\{align\*\}", repl, text, flags=re.S)


def remove_blank_lines_in_captions(text: str) -> str:
    out, i = [], 0
    key = "\\caption{"
    while True:
        j = text.find(key, i)
        if j < 0:
            out.append(text[i:])
            break
        out.append(text[i:j + len(key)])
        depth, k = 1, j + len(key)
        while depth and k < len(text):
            c = text[k]
            if c == "\\":
                k += 2
                continue
            if c == "%":  # skip comment to end of line
                k = text.find("\n", k)
                k = len(text) if k < 0 else k
                continue
            depth += c == "{"
            depth -= c == "}"
            k += 1
        arg = text[j + len(key):k]
        arg = re.sub(r"\n\s*\n", "\n", arg)
        # deleted sectioning commands inside a caption are meaningless; keep them as comments only
        out.append(arg)
        i = k
    return "".join(out)


def drop_deleted_bibliography(text: str) -> str:
    """Replace both the deleted original reference list and the flattened new .bbl by \\bibliography.

    The reference list was rebuilt from scratch (see docs/reference_audit.md), so a
    word-level diff of it is meaningless; BibTeX regenerates the new list unmarked.
    """
    start = text.find("%DIFDELCMD < \\begin{thebibliography}")
    if start < 0:
        start = text.find("\\begin{thebibliography}")
    if start < 0:
        return text
    begin_line = text.rfind("\n", 0, start) + 1
    end = text.rfind("\\end{document}")
    note = ("% The original hand-written reference list was replaced in full; the new list is generated by BibTeX.\n"
            "\\bibliographystyle{unsrtnat}\n\\bibliography{references}\n\n")
    return text[:begin_line] + note + text[end:]


def neutralise_dangling_references(text: str, bib: Path) -> str:
    """Deleted original text may refer to labels/citations that no longer exist; show them as plain text."""
    uncommented = re.sub(r"(?<!\\)%.*", "", text)  # labels inside %DIFDELCMD comments do not exist
    labels = set(re.findall(r"\\label\{([^}]*)\}", uncommented))
    keys = set(re.findall(r"@\w+\{([^,]+),", bib.read_text(encoding="utf-8"))) if bib.exists() else set()

    def ref(m):
        return m.group(0) if m.group(2) in labels else "[removed reference]"

    def cite(m):
        ks = [k.strip() for k in m.group(1).split(",")]
        return m.group(0) if all(k in keys for k in ks) else "[" + ", ".join(ks) + "]"

    text = re.sub(r"\\(ref|eqref)\{([^}]*)\}", ref, text)
    return re.sub(r"\\cite\{([^}]*)\}", cite, text)


def main(path: str) -> None:
    p = Path(path)
    t = p.read_text(encoding="utf-8")
    t = strip_labels_in_deleted_math(t)
    t = remove_blank_lines_in_captions(t)
    t = drop_deleted_bibliography(t)
    t = neutralise_dangling_references(t, p.parent / "references.bib")
    t = t.replace("\\graphicspath{{figures/}}", "\\graphicspath{{figures/}{../original/}}")
    # deleted and added sections share counter values; unique hyperlink anchors avoid duplicate-destination warnings
    t = t.replace("\\usepackage[hidelinks]{hyperref}", "\\usepackage[hidelinks,hypertexnames=false]{hyperref}")
    p.write_text(t, encoding="utf-8")
    print("post-processed", p)


if __name__ == "__main__":
    main(sys.argv[1])
